export const FETCH_BOOKS_DATA_REQUEST = 'FETCH_BOOKS_DATA_REQUEST'
export const SET_BOOKS_SUCCES = 'SET_BOOKS_SUCCES'

export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_FROM_CARD = 'DELETE_FROM_CARD'
export const DELETE_ALL_BY_ID = 'DELETE_ALL_BY_ID'